name: smartlock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  local_auth: ^2.2.0
  qr_flutter: ^4.1.0
  share_plus: ^9.0.0
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  fl_chart: ^0.68.0
  flutter_tts: ^3.8.3
  sleek_circular_slider: ^2.1.0

  # Firebase packages (alineados al mismo nivel que los anteriores)
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
